### ISSUE TITLE
Can you upload your paper?

### ISSUE THREAD

**Issue by Space4ARDev** [Chen-Xieyuanli/Relocalization-ORB-SLAM#2]
I want to read your paper.

Can you upload your paper "Robust Relocalization Based on Active Loop Closure for Real-Time Monocular SLAM"?

**Comment by Chen-Xieyuanli** [comment]
Hey there,

I am quite glad you are interested in my paper, and you could find the paper in my [ResearchGate](https://www.researchgate.net/publication/318307400_Robust_Relocalization_Based_on_Active_Loop_Closure_for_Real-Time_Monocular_SLAM).

Best,
Xieyuanli Chen
